// Tournament data for API
const tournament = {
  id: 'sahara-cup-2025',
  name: 'Sahara Cup 2025',
  description: 'Annual Table Tennis Tournament',
  startDate: '2025-07-15T09:00:00Z',
  endDate: '2025-07-18T18:00:00Z',
  status: 'active',
  players: [
    { id: 'p1', name: 'Anjuman Hasan', email: 'anjuman@company.com' },
    { id: 'p2', name: 'Anusha Reddy Bakaram', email: 'anusha@company.com' },
    { id: 'p3', name: 'Arishti Salaria', email: 'arishti@company.com' },
    { id: 'p4', name: 'Bhavani Parupureddy', email: 'bhavani@company.com' },
    { id: 'p5', name: 'Durga Tammireddy', email: 'durga@company.com' },
    { id: 'p6', name: 'Induja Kala', email: 'induja@company.com' },
    { id: 'p7', name: 'Jyothi M', email: 'jyothi@company.com' },
    { id: 'p8', name: 'Krishna Ramya', email: 'krishna@company.com' },
    { id: 'p9', name: 'Manaswini Pidugu', email: 'manaswini@company.com' },
    { id: 'p10', name: 'Prathyusha Dodda', email: 'prathyusha@company.com' },
    { id: 'p11', name: 'Rubeena Khatun', email: 'rubeena@company.com' },
    { id: 'p12', name: 'Sai Keerthi Tulluru', email: 'saikeerthi@company.com' },
    { id: 'p13', name: 'Sanchita Chakrabarty Ma\'am', email: 'sanchita@company.com' },
    { id: 'p14', name: 'Sanu Gupta', email: 'sanu@company.com' },
    { id: 'p15', name: 'Shreeya Dheera Parvatham', email: 'shreeya@company.com' },
    { id: 'p16', name: 'Siddhi Goyal', email: 'siddhi@company.com' },
    { id: 'p17', name: 'Sneha Sai Pola', email: 'sneha@company.com' },
    { id: 'p18', name: 'Sri Indu Dekkapati', email: 'sriindu@company.com' },
    { id: 'p19', name: 'Srija Panyala', email: 'srija@company.com' },
    { id: 'p20', name: 'Tamanna Koundal', email: 'tamanna@company.com' },
    { id: 'p21', name: 'Treesa James', email: 'treesa@company.com' },
    { id: 'p22', name: 'Tulsi Pratyusha Dintyala', email: 'tulsi@company.com' },
    { id: 'p23', name: 'Vaishnavi Sindham', email: 'vaishnavi@company.com' },
    { id: 'p24', name: 'Yadavalli Dedeepya Sneha', email: 'yadavalli@company.com' },
  ],
  groups: [
    { id: 'g1', name: 'Group A', playerIds: ['p21', 'p5', 'p8'] },
    { id: 'g2', name: 'Group B', playerIds: ['p13', 'p1', 'p15'] },
    { id: 'g3', name: 'Group C', playerIds: ['p19', 'p3', 'p4'] },
    { id: 'g4', name: 'Group D', playerIds: ['p6', 'p12', 'p10'] },
    { id: 'g5', name: 'Group E', playerIds: ['p20', 'p22', 'p24'] },
    { id: 'g6', name: 'Group F', playerIds: ['p2', 'p9', 'p17'] },
    { id: 'g7', name: 'Group G', playerIds: ['p11', 'p18', 'p23'] },
    { id: 'g8', name: 'Group H', playerIds: ['p7', 'p14', 'p16'] },
  ],
  matches: [],
  knockoutMatches: []
};

module.exports = { tournament };
